### ISSUE TITLE
Preview.yml が Fork した人からの PR で失敗する

### ISSUE THREAD

**Issue by terasakisatoshi** [AtelierArith/OkinawaCompPhysFoodSurvey2024.jl#9]
現象

https://github.com/AtelierArith/OkinawaCompPhysFoodSurvey2024.jl/actions/runs/8182342029/job/22373540766?pr=7

**Comment by terasakisatoshi** [comment]
プッシュの権限が他の人からできないからだと思う．

**Comment by terasakisatoshi** [comment]
ひとまず下記の yml において，トリガーを workflow_dispatch にするかな．

```
name: PreviewPages
on:
  #push:
  #  branches:
  #    - '!main'
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  docs:
    name: DocTest
    runs-on: ubuntu-latest
    permissions:
      actions: write # needed to allow julia-actions/cache to proactively delete old caches that it has created
      contents: write
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - name: Configure Fonts
        run: |
          sudo get update && apt-get install fontconfig
          bash tools/fonts/download_juisee.sh
      - name: Configure doc environment
        shell: julia --project=docs --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run doctests
        shell: julia --project=docs --color=yes {0}
        run: |
          using Documenter: DocMeta, doctest
          using OkinawaCompPhysFoodSurvey2024
          DocMeta.setdocmeta!(OkinawaCompPhysFoodSurvey2024, :DocTestSetup, :(using OkinawaCompPhysFoodSurvey2024); recursive=true)
          doctest(OkinawaCompPhysFoodSurvey2024)
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Document generation succeeded!
            Preview site will be available at https://atelierarith.github.io/OkinawaCompPhysFoodSurvey2024.jl/previews/PR${{ github.event.number }} after github-pages deployment🚀
          token: ${{ secrets.GITHUB_TOKEN }}
```
